version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/myapi
  - source: myapi.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 180
      runas: root
