name: Build and Deploy MyApi Applications

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_PATH: "MyApi/MyApi.csproj"
  DOTNET_VERSION: "9.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        working-directory: src
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ./publish --self-contained true -r linux-x64

      - name: Zip deployment artifact
        working-directory: src
        run: |
          cp ./MyApi/appspec.yml ./publish/
          cp ./MyApi/myapi.service ./publish/
          cp -r ./MyApi/scripts ./publish/
          cd publish
          zip -r ../../myapi-deploy.zip .

      - name: Upload artifact to S3
        run: |
          aws s3 cp myapi-deploy.zip s3://$CODEDEPLOY_BUCKET/myapi-deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CODEDEPLOY_BUCKET: ${{ secrets.CODEDEPLOY_BUCKET }}

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} --deployment-group-name ${{ secrets.CODEDEPLOY_DEPLOYMENT_GROUP }} --s3-location bucket=${{ secrets.CODEDEPLOY_BUCKET}},bundleType=zip,key=myapi-deploy.zip --file-exists-behavior OVERWRITE
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CODEDEPLOY_BUCKET: ${{ secrets.CODEDEPLOY_BUCKET }}
